
name: Convert CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Neovim
      run: |
        sudo apt-get update
        sudo apt-get install -y neovim

    - name: Set up LuaRocks
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: '5.1'

    - name: Install dependencies
      run: |
        luarocks install busted
        git clone https://github.com/notomo/vusted.git

    - name: Run tests
      run: |
        nvim --headless -c "lua require('vusted.runner')({dir='tests'})"
